### ISSUE TITLE
Release tracker - v0.2.0

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-vision#139]
This issue is to be used to track the roadmap of pyrovision for release v0.2.0, and collect feedback from users & contributors.

- Datasets
    - [x] #153
- Models
    - [x] Deprecates inhouse models & use external sources for architecture definition (#138)
    - [x] #150 
    - [x] #123
- NN
    - [x] Deprecates the entire module  (#138)
- References
    - [x] Updates training script with modern tools (#138)
    - [x] #140 
    - [x] Adds W&B logging (#138)
- Tests
    - [x] Switch to pytest (#138) 
- API
    - [x] Adds a minimal FastAPI template to deploy pyrovision (#152)
- Demo
    - [x] Adds a minimal Streamlit/Gradio demo (#151)
- Other
    - [x] #145

**Comment by frgfm** [comment]
Closed by last release
