### ISSUE TITLE
Release tracker - v0.3.0

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-vision#154]
This issue is to be used to track the roadmap of pyrovision for release v0.3.0, and collect feedback from users & contributors.

- Datasets
    - [ ] Add an object detection dataset

- Models
    - [] Add object detection models 

- References
    - [] Adds object detection training script

- Tests

- API

- Demo
    - [ ] Add an object detection model as a demo

- Other
